test_task:
  container:
    matrix:
      image: python:2.7
      image: python:3.5
      image: python:3.6
      image: python:3.7
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION && echo pylint pytest-cov pytest requests-mock git+https://github.com/nmlorg/ntelebot
    populate_script: pip install pylint pytest-cov pytest requests-mock git+https://github.com/nmlorg/ntelebot
  test_script: pytest && pylint metabot
